# Generated by Django 4.2.30 on 2026-05-24 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre/Número de aula')),
                ('capacidad', models.PositiveSmallIntegerField(verbose_name='Capacidad (alumnos)')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='Ubicación / Edificio')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la carrera')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado')], max_length=3, verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Enero-Junio 2026', max_length=50, verbose_name='Nombre del periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=False, verbose_name='Periodo activo')),
            ],
            options={
                'verbose_name': 'Periodo Semestral',
                'verbose_name_plural': 'Periodos Semestrales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('especialidad', models.CharField(blank=True, max_length=150, verbose_name='Especialidad')),
                ('numero_empleado', models.CharField(max_length=20, unique=True, verbose_name='No. Empleado')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la materia')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave')),
                ('creditos', models.PositiveSmallIntegerField(verbose_name='Créditos')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolar.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['carrera', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: A, B, G1, G2', max_length=10, verbose_name='Nombre/Clave del grupo')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.aula', verbose_name='Aula')),
                ('estudiantes', models.ManyToManyField(blank=True, to='escolar.estudiante', verbose_name='Estudiantes inscritos')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.horario', verbose_name='Horario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.materia', verbose_name='Materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.periodosemestral', verbose_name='Periodo semestral')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['periodo', 'materia', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolar.estudiante', verbose_name='Estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolar.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['grupo', 'estudiante'],
                'unique_together': {('estudiante', 'grupo')},
            },
        ),
    ]
